---
 - name: Install Bodo Environment
   include_tasks: conda/environment.yaml
   with_items:
     - bodo

 - name: Ensure bodo license directory exists
   become: true
   file:
     path: "{{ miniforge.home }}/envs/bodo/share/bodo"
     state: directory
     mode: '0755'

 - name: Write bodo license
   become: true
   copy:
     content: "{{ bodo.license }}"
     dest: "{{ miniforge.home }}/envs/bodo/share/bodo/bodo.license"
     mode: '644'

 - name: Ensure bodo.sh activated in shell
   become: true
   copy:
     content: |
       export BODO_LICENSE={{ miniforge.home }}/envs/bodo/share/bodo/bodo.license
     dest: "/etc/profile.d/bodo.sh"
     mode: '755'
