---
 - name: Add apt keys for grafana
   become: true
   apt_key:
     url: "https://packages.grafana.com/gpg.key"
     state: present

 - name: Add apt repository for grafana
   become: true
   apt_repository:
     repo: "deb https://packages.grafana.com/oss/deb stable main"

 - name: Install grafana
   become: true
   apt:
     name: grafana
     state: latest
     cache_valid_time: 3600

 - name: Copy grafana datasource provision file
   become: true
   template:
     src: templates/grafana-datasources.yaml.j2
     dest: /etc/grafana/provisioning/datasources/grafana-datasources.yaml
     owner: root
     group: grafana
     mode: 0440
   register: _grafana_provision_datasource

 - name: Copy grafana dashboard provision file
   become: true
   template:
     src: templates/grafana-dashboards.yaml.j2
     dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
     owner: root
     group: grafana
     mode: 0440
   register: _grafana_provision_dashboard

 - name: Copy grafana dashboards
   become: true
   copy:
     src: "files/dashboards/{{ item }}.json"
     dest: "/etc/grafana/provisioning/dashboards/{{ item }}.json"
     owner: root
     group: grafana
     mode: 0440
   with_items:
     - jupyterhub
     - node_exporter
     - slurm_exporter
     - traefik
   register: _grafana_dashboards

 - name: Copy Grafana Configuration
   become: true
   template:
     src: templates/grafana.ini.j2
     dest: /etc/grafana/grafana.ini
     owner: root
     group: grafana
     mode: 0440
   register: _grafana_configuration

 - name: Ensure granfana is started
   become: true
   service:
     name: grafana-server
     enabled: true
     state: restarted
   when: _grafana_configuration.changed or _grafana_provision_dashboard.changed or _grafana_provision_datasource.changed or _grafana_dashboards.changed
