---
 - name: Install nfs
   become: true
   apt:
     state: latest
     cache_valid_time: 3600
     name:
       - nfs-common
       - nfs-server

 - name: Ensure nfs directory created
   become: true
   file:
     path: "{{ item }}"
     state: directory
   with_items: "{{ nfs_server.exports }}"

 - name: nfs configuration
   become: true
   copy:
     content: |
       {% for export in nfs_server.exports %}
       {{ export }}     *(rw,sync,no_root_squash,no_subtree_check)
       {% endfor %}
     dest: /etc/exports
     mode: '0600'
     owner: root
     group: root

 - name: Ensure nfs server is started
   become: true
   systemd:
     daemon_reload: true
     name: nfs-kernel-server
     enabled: true
     state: restarted
