---
 - name: Install munge
   include_tasks: munge.yaml

 - name: Install slurm client packages
   become: true
   apt:
     state: latest
     cache_valid_time: 3600
     name:
       - slurm-client
       - slurm-wlm-doc

 - name: Build hosts file on slurm nodes
   become: true
   lineinfile:
     dest: /etc/hosts
     regexp: '.*{{ item }}$'
     line: '{{ hostvars[item].ansible_host }} {{item}}'
     state: present
   with_items: '{{ groups["all"] }}'

 - name: ensure that slurm configuration directory exists
   become: true
   file:
     path: /etc/slurm-llnl
     state: directory
     mode: '0755'
     owner: root
     group: root

 - name: install slurm.conf
   become: true
   template:
     src: "templates/slurm.conf.j2"
     dest: "/etc/slurm-llnl/slurm.conf"
     owner: root
     group: root
     mode: 0444
   register: _slurm_config

 - name: Install extra execution host configs
   become: true
   copy:
     content: |
       CgroupAutomount=yes
       ConstrainCores=yes
       ConstrainRAMSpace=yes
       ConstrainSwapSpace=yes
     dest: "/etc/slurm-llnl/cgroup.conf"
     owner: root
     group: root
     mode: 0444
   register: _slurm_cgroup_config
